name: contas_app
description: Aplicativo para pagamento de contas.
publish_to: 'none'

version: 2.4.0+6

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  finance_app:
    path: packages/finance_app

  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.0

  # Necessário para inicialização do módulo finance_app em desktop
  sqflite_common_ffi: ^2.4.0+1
  path: ^1.9.0
  path_provider: ^2.1.0

  # EXPORTAÇÃO PDF
  pdf: ^3.11.0
  printing: ^5.12.0

  # GRÁFICOS
  fl_chart: ^1.1.1
  window_manager: ^0.5.1

  # FILE PICKER
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
