name: finance_app
description: Consultor Financeiro - Gestão de Contas a Pagar
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Banco de Dados
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0

  # UI e Formatação
  google_fonts: ^6.1.0
  intl: ^0.20.2
  brasil_fields: ^1.15.0
  http: ^1.2.2

  # Persistência de Configurações
  shared_preferences: ^2.2.0
  file_picker: ^8.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
